global:
  scrape_interval: 15s
  evaluation_interval: 15s
    
# Monitoring for default scrape path /metrics
  
scrape_configs:
 - job_name: 'services'
   scrape_interval: 5s
   metrics_path: '/metrics'
   consul_sd_configs:
   - server: consul.service.local:8500
     token: ${CONSUL_TOKEN}
     tag: 'metrics-default'
   relabel_configs:
   - source_labels:
     - '__meta_consul_service'
     target_label: 'service'
   - source_labels:
     - '__meta_consul_service_address'
     target_label: 'address'
     
rule_files:
- 'rules/*.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager.service.local:9093'
